website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Club, Links
from werkzeug.security import generate_password_hash, check_password_hash 
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from .sendmail import send_mail, send_alt_mail
from .forms import LoginForm, SignupForm

auth = Blueprint("auth", __name__)

@auth.route("/login", methods=["GET", "POST"]) 
def login():
    form = LoginForm()

    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        if email and password:
            user = User.query.filter_by(email=email).first() # Filters all of the users who have this email.
            if user: # If this user is found: 
                if check_password_hash(user.password, password): # Checks this user's password.
                    flash(f"Successfully logged in as {user}", category="success")
                    login_user(user, remember=True) # Logs in the user. Remembers the fact that this user is logged in until the user clears their browser history / session. Will be stored in the flask webserver - until the webserver restarts. 
                    return redirect("/")
                    # return render_template("layout.html", club_info=Club.query.all(), joined_clubs=current_user.clubs, user=current_user)
                else:
                    flash("Incorrect password, try again!", category="error")
            else: # If this user is not found:
                flash("This email does not belong to an account. Try creating a new account!", category="error")

        submit = request.form.get("loginasguest")
        print(f"20 - {submit}") 

        if submit == "Login as Guest":
            print("33 - ok")
            guest_user = User.query.filter_by(email="25guestuser123@cpsd.us").first()
            if guest_user:
                print("Found the guest user.")
                login_user(guest_user, remember=True)
                flash(f"Successfully logged in as {guest_user}", "success")
                return redirect("/")
            else:
                print("No guest user found!")
        else:
            print("DIdn't register logging in as a guest.")

    return render_template("login.html", user=current_user, name="auth", form=form, links=Links.query.all())

def check_email(email):
    ind_at = email.index("@")
    rest = email[ind_at:]
    try:
        if rest.index("cpsd.us") > 0:
            return True
        return False
    except:
        return False

@auth.route("/signup", methods=["GET", "POST"]) 
def signup(): 
    form = SignupForm()

    if request.method == "POST":
        email = request.form.get("email")
        if not check_email(email):
            flash("Email needs to be a cpsd email.", "error")
            return redirect("/signup")
        password = request.form.get("password")
        confirm_password = request.form.get("confirm_password") 
        role = "Member"
        if email[0].isnumeric():
            role = "Member"
        else: role = "Advisor"

        # Makes sure two users don't use the same email address: 
        user = User.query.filter_by(email=email).first() 
        if user: 
            flash("This email is already linked to an account!", category="error") 
        elif len(email) < 4: 
            flash("Your email must be greater than 3 characters!", category="error")
        elif password != confirm_password:
            flash("Your passwords do not match!", category="error") 
        elif len(password) < 7:
            flash("Your password must be greater than 6 characters!", category="error")
        else:
            new_user = User(email=email, password=generate_password_hash(password, method="sha256"), is_leader=False, role=role)
            db.session.add(new_user) 
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Your account has been created!", category="success")
            return redirect("/")

    return render_template("signup.html", user=current_user, name="auth", form=form, links=Links.query.all())

@auth.route("/logout") 
@login_required # Makes sure we cannot access this route / page unless the user is logged in - can't logged out if not logged in.  
def logout():
    logout_user() # Logs out the current user. 
    flash("Logged out", category="success")
    return redirect(url_for("auth.login"))

@auth.route("/<id>/<stage>/forgotpassword", methods=["GET", "POST"])
def forgot_password(id, stage):
    if stage == "email":
        if request.method == "POST":
            email = request.form.get("email")
            user = User.query.filter_by(email=email).first()
            if user:
                email_sender = "crlsclubfinder@gmail.com"
                email_password = "wmzhhaxtzqnvyuze"
                email_receiver = email
                subject = "Change ClubFinder Pasword"
                text = f"Follow this link to change your password: https://www.crlsclubfinder.com/{user.id}/changepassword/"
                html = f"""
<h2>Change Password</h2>
<p>Click the button below to change your password</p>
<button class="clubbutton" type="submit"><a href='https://www.crlsclubfinder.com/{user.id}/changepass/forgotpassword'>Change Password</a></button>
"""
                send_alt_mail(email_sender=email_sender, email_password=email_password, email_receiver=email_receiver, subject=subject, text=text, html=html)
                flash("Email successfully sent!", "success")
            else:
                flash("This email is not linked with an account.", "error")
                return redirect("/forgotpassword/email")
        return render_template("forgotpassword.html", user=current_user, stage=stage, links=Links.query.all())
    
    if stage == "changepass":
        if request.method == "POST":
            id = request.form.get("id")
            user = User.query.filter_by(email=id).first()
            if user is not None:
                id = user.id
                print(f"121 - {id}")
                new_password = request.form.get("newpassword")
                confirm_new_password = request.form.get("confirm-newpassword")
                if new_password != confirm_new_password:
                    flash("Passwords don't match.", "error")
                    return redirect("/changepass/forgotpassword")
                new_password = generate_password_hash(new_password, method="sha256")
                print(f"128 Old Pass - {user.password}")
                user.password = new_password
                db.session.commit()
                print(f"131 New Pass - {user.password}")
                flash("Successfully changed password!", "success")
                return redirect("/login")
            else: flash("No user")
        return render_template("forgotpassword.html", user=current_user, stage=stage, id=id, links=Links.query.all())
        
        # Find and change this password. 
    
    return render_template("forgotpassword.html", user=current_user, stage=stage, links=Links.query.all())

@auth.route("/<id>/changepassword", methods=["GET", "POST"])
def changepass(id):
    return redirect("/id/forgotpassword")
    # return redirect(url_for("auth.forgot_password", stage="changepass"))

website/templates/becomeamentor.html
{% extends "layout.html" %}

{% block title %}Signup{% endblock %}

{% block body %}

<div class="multistepwrapper">
  {% if step == "basicinfo" %}

  <div class="infowrapper">
      <form action="{{ url_for('auth.signup', step='morespecific') }}" class="signupform" method="POST">
          <div class="stepmenu">
              <ul>
                  <li class="formbold-step-menu1 active">
                      <span>1</span>
                      <a href="/signup/basicinfo">Basic Info</a>
                  </li>
                  <li class="formbold-step-menu2">
                      <span>2</span>
                      More Specific
                  </li>
                  <li class="formbold-step-menu3">
                      <span>3</span>
                      Confirm
                  </li>
              </ul>
          </div>
  
          <div class="basicinfocontent">
            <div class="formbold-input-flex">
              <div>
                  <!-- Source: https://stackoverflow.com/questions/34738331/using-flask-wtforms-how-do-i-style-my-form-section-of-the-html -->
                  {{ form.firstname.label(class="formbold-form-label") }} 
                  {{ form.firstname(class="formbold-form-input") }}
              </div>
              <div>
                  {{ form.lastname.label(class="formbold-form-label") }} 
                  {{ form.lastname(class="formbold-form-input") }}
              </div>
            </div>
            <div class="formbold-input-flex">
                <!-- <div>
                  {{ form.dob.label(class="formbold-form-label") }} 
                  {{ form.dob(class="formbold-form-input") }}
                </div> -->
                <div>
                  {{ form.email.label(class="formbold-form-label") }} 
                  {{ form.email(class="formbold-form-input") }}
                </div>
                <div>
                    {{ form.password.label(class="formbold-form-label") }} 
                    {{ form.password(class="formbold-form-input") }}
                </div>
            </div>
            <!-- <div class="formbold-input-flex"> -->
              <div>
                  {{ form.confirmpassword.label(class="formbold-form-label") }} 
                  {{ form.confirmpassword(class="formbold-form-input") }}
              </div>
            <!-- </div> -->
            <!-- Add a confirmation password div here and wrap both divs in the same flex div as above. -->
            <!-- <button class="nextstep" type="submit">Next Step</button> -->
            {{ form.submit(class="nextstep") }}
      </form>
  </div>

  {% elif step == "morespecific" %}

  <div class="infowrapper">
      <form action="{{ url_for('findamentor.becomeamentor', step='confirm') }}" class="signupform" method="POST">

          <div class="stepmenu">
              <ul>
                  <li class="formbold-step-menu1">
                      <span>1</span>
                      <a href="/signup/basicinfo">Basic Info</a>
                  </li>
                  <li class="formbold-step-menu2 active">
                      <span>2</span>
                      <a href="/signup/morespecific">More Specific</a>
                  </li>
                  <li class="formbold-step-menu3">
                      <span>3</span>
                      Confirm
                  </li>
              </ul>
          </div>

          <div class="infocontent">
              <ul class="mainselector">

                <li class="buttonwrapper">
                  <div class="selectortitlewrapper">
                    <p class="selectortitle">{{ form.mentormentee.label }}</p>
                  </div>
                  {% for item in form %} 
                  
                    {# {% for sub in item %}

                      <div class="selectoritem">
                        <label class="buttonlabel">
                          {{ sub }}
                          {{ sub.label }}
                          <span class="checkmark" id="radiocheck"></span>
                        </label>
                      </div>

                    {% endfor %} #}

                      

                    </li>
                  
                  {% endfor %}


                    

                    <div class="hiddenselector">
                      <input type="text" name="email" value="{{ email }}" hidden>
                    </div>
                </ul>
          </div>
          {{ form.submit(class="nextstep") }}
      </form>
  </div>

  {% elif step == "confirm" %}

  <div class="infowrapper">
    <div class="stepmenu">
      <ul>
          <li class="formbold-step-menu1">
              <span>1</span>
              <a href="/signup/basicinfo">Basic Info</a>
          </li>
          <li class="formbold-step-menu2">
              <span>2</span>
              <a href="/signup/morespecific">More Specific</a>
          </li>
          <li class="formbold-step-menu3 active">
              <span>3</span>
              Confirm
          </li>
      </ul>
  </div>
    <div class="steptitle">Confirm Your Information</div>
    <div class="confirmbody">
      <form action="{{ url_for('auth.signup', step='finish') }}" class="signupform" method="POST">
        <div class="confirmtext">
          <div class="confirmanschoi">
            <div class="confirmcat">
              Mentee/Mentor:
            </div>
            <div class="confirmchoice">
              {% if mentormentee == "Mentor" %}Mentor{% else %}Mentee{% endif %}
            </div>
          </div>
          {% for item in form %}
          {{ item }}
          {% endfor %}
          <div class="confirmanschoi">
            <div class="confirmcat">
              Race:
            </div>
            <div class="confirmchoice">
              {{ race }}
            </div>
          </div>
          <div class="confirmanschoi">
            <div class="confirmcat">
              Religion:
            </div>
            <div class="confirmchoice">
              {{ religion }}
            </div>
          </div>
          <div class="confirmanschoi">
            <div class="confirmcat">
              Gender:
            </div>
            <div class="confirmchoice">
              {{ gender }}
            </div>
          </div>
          <div class="confirmanschoi">
            <div class="confirmcat">
              Languages:
            </div>
            <div class="confirmchoice">
              {{ languages }}
            </div>
          </div>
          <div class="confirmanschoi">
            <div class="confirmcat">
              Academics
            </div>
            <div class="confirmchoice">
              {{ academics }}
            </div>
          </div>
        </div>
        <div class="controlbutton">
          {{ form.submit(class="nextstep") }}
          <button class="nextstep goback" type="submit" id="goback"><a href="/signup/morespecific">Back</a></button>
        </div>
        
      </form>
    </div>
  </div>

  {% elif step == "finish" %}

  <div class="infowrapper">
    <div class="steptitle">Sign up complete!</div>
    <div class="finishbody">
      <p class="finishtext">
        Sign up is complete! 
        <br>
        Please click <b>here</b> to explore the possibilities of being a mentor/mentee, or click <b>here</b> to return to the main page!
        <br>
        Thank you!
      </p>
    </div>
  </div>

  {% endif %}

</div>

{% endblock %}

website/templates/clubcard.html
<!-- Clubs are added here: -->
{% for club in club_info %}
    {% if club.status == "Approved" %}
    <div class="club" id="{{ club.club_name }}1"> <!-- Card -->
        <div class="clubcontent" id="content{{ club.id }}"> <!-- Card content -->
            <div class="clubtitle" id="content{{ club.id }}">
                {{ club.club_name }}{% if club in joined_clubs %} <i class="fa-solid fa-star"></i>{% endif %} {% if current_user.email == club.president_email or current_user.email == club.vicepresident_email1 or current_user.email == club.vicepresident_email2 or current_user.email == club.vicepresident_email3 %}<i class="fa-solid fa-crown"></i>{% endif %}
            </div> <!-- Card title  -->
            <br>
            <p class="shortdesc" id="content{{ club.id }}">
                Club President: {{ club.president_email }}
                <br><br>
                Meets {% if club.start_time %} at {% endif %}{{ club.start_time }} on {{ club.club_day }} <br>
            </p> <!-- Card body -->
            <!-- Modal: -->
            <dialog class="clubdesc" id="clubdesc_{{ club.id }}">
                <div class="clubdescheader">
                    <div class="clubdescname">{{ club.club_name }}</div>
                    <div class="closebuttonwrapper"></div>
                    <button data-close-button id="clubclosebutton_{{ club.id }}" class="clubclosebutton">&times;</button>
                </div>
                <div class="clubdescdesc" id="clubdescdesc{{ club.club_name }}">
                    Club President: {{ club.president_email }}
                        <br><br>
                        {% if club.vicepresident_email1 or club.vicepresident_email2 or club.vicepresident_email3 %}
                        Vice President{% if club.vicepresident_email1 and club.vicepresident_email2 %}s{% endif %}:
                        {{ club.vicepresident_email1 }}<br/><br/>
                        {% endif %}
                        {% if club.vicepresident_email2 %}
                        ,&nbsp;{{ club.vicepresident_email2 }}<br/><br/><br/>
                        {% endif %}
                        {% if club.vicepresident_email3 %}
                        ,&nbsp;{{ club.vicepresident_email3 }}<br><br><br>
                        {% endif %} 
                    Meets in room {{ club.room_number }} <br><br>
                    Club Advisor: {{ club.advisor_email }}
                    <br><br>
                    <!-- Club Description: --> {{ club.description }}
                    <br><br>
                </div>
            </dialog>
            <!-- ^ End of Modal ^ -->
            <br><br>
            {% if club not in joined_clubs %}
            <form method="POST" class="joinclubbutton" action="{{ url_for('clubs.join', id=club.id) }}">
                <button class="clubbutton" type="submit">Join {{ club }}</button> 
            </form>
            {% elif club in joined_clubs %}
            <form method="POST" class="joinclubbutton" action="{{ url_for('clubs.leave', id=club.id) }}">
                <button class="clubbutton" type="submit">Leave {{ club }}</button> 
            </form>
            {% endif %}
        </div>
        
    </div>
    <!-- <dialog class="successfullyjoinedclubmodal_{{ club.id }}" id="succclub">
        <div class="succjoinedclubmodalcontent">
            <button data-close-button id="succclubclosebutton_{{ club.id }}" class="clubclosebutton">&times;</button>
            <p class="succjoinedclubmodaltext">
                Successfully joined {{ club.club_name }}!
                <br>
                Please check your email for more information about the club.
            </p>
        </div>
    </dialog>
    <dialog class="successfullyleftclubmodal_{{ club.id }}" id="succclub">
        <div class="succleftclubmodalcontent">
            <button data-close-button id="succleftclubclosebutton_{{ club.id }}" class="clubclosebutton">&times;</button>
            <p class="succleftclubmodaltext">
                Successfully left {{ club.club_name }}
            </p>
        </div>
    </dialog> -->
    {% endif %}
{% endfor %}

website/templates/clubs.html
{% extends "layout.html" %}

{% block body %}

<h1 id="main1"><center>My Clubs:</center></h1>

<!-- The Main Container (where the clubs are held): -->
<div class="maincontainer" id="maincontainer"> 
    <!-- Clubs are added here: -->
    {% for club in club_info %}
        <div class="club" id="{{ club.club_name }}1"> <!-- Card -->
            <div class="clubcontent" id="{{ club.club_name }}"> <!-- Card content -->
                <div class="clubtitle" id="{{ club.club_name }}1">{{ club.club_name }}</div> <!-- Card title  -->
                <br><br>
                <button formTarget="#clubdesc_{{ club.id }}" class="clubbutton" id="viewclub" type="button">View More</button> <!-- Button -->
                <p class="shortdesc">
                    Club President: {{ club.president_email }}
                </p> <!-- Card body -->
                <!-- Modal: -->
                <dialog class="clubdesc" id="clubdesc_{{ club.id }}">
                    <div class="clubdescheader">
                        <div class="clubdescname">Join {{ club.club_name }}</div>
                        <button data-close-button id="clubclosebutton_{{ club.id }}" class="clubclosebutton">&times;</button>
                    </div>
                    <div class="clubdescdesc" id="clubdescdesc{{ club.club_name }}">
                        Club President: {{ club.president_email }}
                        <br><br>
                        {% if club.vicepresident_email1 %}Vice President{% if club.vicepresident_email1 and club.vicepresident_email2 %}s{% endif %}: {{ club.vicepresident_email1 }}{% endif %}{% if club.vicepresident_email2 %},&nbsp;{{ club.vicepresident_email2 }}{% endif %}{% if club.vicepresident_email3 %},&nbsp;{{ club.vicepresident_email3 }} {% endif %}
                        <br><br> 
                        Club Advisor: {{ club.advisor_email }}
                        <br><br>
                        Club Description: {{ club.description }}
                        <br><br>
                        {{ club.club_name }} is located in room {{ club.room_number }}, and starts at {{ club.start_time }}.
                    </div>
                </dialog>
                <!-- ^ End of Modal ^ -->
                <br><br>
                <button method="GET" name="leaveclubbutton_{{ club.id }}" class="clubbutton" id="leaveclubbutton_{{ club.id }}" type="button">Leave Club</button> 
            </div>
            
        </div>
    {% endfor %}
</div>

{% endblock %}

website/templates/createaclub.html
{% extends "layout.html" %}

{% block title %} Register Your Club {% endblock %}

{% block body %}

<div class="makeaclubok">
    <div class="title">Register Your Club</div>
    <form action="#" method="POST">
        <div class="userdetails">
            <div class="userdetailsmain">
                <div class="inputbox">
                    <span class="details">Club Name <i class="fa-solid fa-star-of-life" id="clubname" style="color: #ff0000;"></i></span>
                    <input type="text" placeholder="Club Name" name="clubname" required>
                </div>
                <div class="inputbox">
                    <span class="details">President's Email <i class="fa-solid fa-star-of-life" id="presidentemail" style="color: #ff0000;"></i></span>
                    <input type="text" placeholder="clubpresident@cpsd.us" name="presidentemail" required>
                </div>
                <div class="inputbox">
                    <span class="details">Vice President's Email</span>
                    <input type="text" placeholder="clubvicepresident@cpsd.us (if any)" name="vicepresidentemail1" >
                </div>
                <div class="inputbox">
                    <span class="details">Vice President's Email</span>
                    <input type="text" placeholder="clubvicepresident@cpsd.us (if any)" name="vicepresidentemail2">
                </div>
                <div class="inputbox">
                    <span class="details">Vice President's Email</span>
                    <input type="text" placeholder="clubvicepresident@cpsd.us (if any)" name="vicepresidentemail3">
                </div>
                <div class="inputbox">
                    <span class="details">Advisor's Email <i class="fa-solid fa-star-of-life" id="advisoremail" style="color: #ff0000;"></i></span>
                    <input type="text" placeholder="clubadvisor@cpsd.us" name="advisoremail" required>
                </div>
                <div class="inputbox">
                    <span class="details">Room Number <i class="fa-solid fa-star-of-life" id="roomnumber" style="color: #ff0000;"></i></span>
                    <input type="number" placeholder="Room Number" name="roomnumber" required>
                </div>
                <div class="inputbox">
                    <span class="details">Club Start Time <i class="fa-solid fa-star-of-life" id="clubstarttime" style="color: #ff0000;"></i></span>
                    <input type="time" placeholder="Start time" name="clubstarttime" required>
                </div>
            </div>
            <div class="inputbox">
                <span class="details">Select which day(s) your club meets: <i class="fa-solid fa-star-of-life" id="clubdays" style="color: #ff0000;"></i></span>
                <div class="clubdaysdaysdays">
                    <div class="day">
                        <input type="checkbox" value="Mondays" name="clubday" id="monday">
                        <label for="monday">Monday</label>
                    </div>
                    <div class="day">
                        <input type="checkbox" value="Tuesdays" name="clubday" id="tuesday">
                        <label for="tuesday">Tuesday</label>
                    </div>
                    <div class="day">
                        <input type="checkbox" value="Wednesdays" name="clubday" id="wednesday">
                        <label for="wednesday">Wednesday</label>
                    </div>
                    <div class="day">
                        <input type="checkbox" value="Thursdays" name="clubday" id="thursday">
                        <label for="thursday">Thursday</label>
                    </div>
                    <div class="day">
                        <input type="checkbox" value="Fridays" name="clubday" id="friday">
                        <label for="friday">Friday</label></div>
                </div>
            </div>
            <br><br><br><br>
            <div class="inputbox">
                <span class="details">Club Description <i class="fa-solid fa-star-of-life" id="clubdescription" style="color: #ff0000;"></i></span>
                <textarea type="text" id="inputthedescription" placeholder="Description of club" name="clubdescription" required></textarea>
            </div>
        </div>
        <div class="button">
            <input type="submit" value="Confirm" class="submitnewclubbutton">
        </div>
    </form>
</div>

{% endblock %}

website/templates/findamentor.html
{% extends "layout.html" %}

{% block title %}Find A Mentor{% endblock %}

{% block body %}

<div class="findmentorbody">
    <div class="findmentortitle">Find Your Mentor</div>
    <div class="findmentorcontainer">
    {% for mentor in mentors %}

    <div class="mentorcardscontainer">
        <div class="mentorcard">
          <div class="box">
            <div class="content">
              <h3>{{ mentor["firstname"] }} {{ mentor["lastname"] }}</h3>
              <div class="speccontent">
                <div class="morecont">
                    Race: {{ mentor["race"] }}
                </div>
                <div class="morecont">
                    Religion: {{ mentor["religion"] }}
                </div>
                <div class="morecont">
                    Gender: {{ mentor["gender"] }}
                </div>
                <div class="morecont">
                    Languages: {{ mentor["languages"] }}
                </div>
                <div class="morecont">
                    Academics: {{ mentor["academics"] }}
                </div>
              </div>
              <a href="#">Read More</a>
            </div>
          </div>
        </div>
    </div>

    {% endfor %}
    </div>
</div>

{% endblock %}

website/templates/joinleavebuttons.html
{% for club in club_info %}
    {% if club not in joined_clubs %}
    <button method="GET" name="joinclubbutton_{{ club.id }}" class="clubbutton" id="joinclubbutton_{{ club.id }}" type="button">Join Club</button>
    <br><br>
    {% elif club in joined_clubs %}
    <button method="GET" name="leaveclubbutton_{{ club.id }}" class="clubbutton" id="leaveclubbutton_{{ club.id }}" type="button">Leave Club</button> 
    <br><br>
    {% endif %}
{% endfor %}

website/templates/login.html
{% extends "layout.html" %}

{% block title %}Login{% endblock %}

{% block body %}

<div class="wrapperwrapper">
    <div class="wrapper">
        <header>Login Form</header>
        <form action="/login" method="POST" class="loginform">
          <div class="field email">
            <div class="input-area">
              <!-- <input type="text" name="email" placeholder="Email Address"> -->
              {{ form.email }}
              <i class="icon fas fa-envelope"></i>
              <i class="error error-icon fas fa-exclamation-circle"></i>
            </div>
            <div class="error error-txt">Email can't be blank</div>
          </div>
          <div class="field password">
            <div class="input-area">
              <!-- <input type="password" name="password" placeholder="Password"> -->
              {{ form.password }}
              <i class="icon fas fa-lock"></i>
              <i class="error error-icon fas fa-exclamation-circle"></i>
            </div>
            <div class="error error-txt">Password can't be blank</div>
          </div>
          <div class="pass-txt"><a href="#">Forgot password?</a></div>
          {{ form.submit }}
        </form>
        <div class="sign-txt">Don't have an account?<a href="/signup"> Sign Up</a></div>
      </div>
</div>

{% endblock %}

website/templates/registeraclub.html
{% extends "layout.html" %}

{% block title %} Register Your Club {% endblock %}

{% block body %}

<div class="makeaclubok">
    <div class="title">Register Your Club</div>
    <form action="#" method="POST">
        <div class="userdetails">
            <div class="userdetailsmain">
                <div class="inputbox">
                    {{ form.clubname.label(class="details") }}
                    {{ form.clubname }}
                </div>
                <div class="inputbox">
                    {{ form.presidentemail.label(class="details") }}
                    {{ form.presidentemail }}
                </div>
                <div class="inputbox">
                    {{ form.vicepresidentemail1.label(class="details") }}
                    {{ form.vicepresidentemail1 }}
                </div>
                <div class="inputbox">
                    {{ form.vicepresidentemail2.label(class="details") }}
                    {{ form.vicepresidentemail2 }}
                </div>
                <div class="inputbox">
                    {{ form.vicepresidentemail3.label(class="details") }}
                    {{ form.vicepresidentemail3 }}
                </div>
                <div class="inputbox">
                    {{ form.advisoremail.label(class="details") }}
                    {{ form.advisoremail }}
                </div>
                <div class="inputbox">
                    {{ form.roomnumber.label(class="details") }}
                    {{ form.roomnumber }}
                </div>
                <div class="inputbox">
                    {{ form.clubstarttime.label(class="details") }}
                    {{ form.clubstarttime }}
                </div>
            </div>
            <div class="inputbox">
                {{ form.clubday.label(class="details") }}
                <div class="clubdaysdaysdays">
                    {% for day in form.clubday %}
                    <div class="day">
                        {{ day }}
                        {{ day.label }}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <br><br><br><br>
            <div class="inputbox">
                {{ form.clubdescription.label(class="details") }}
                {{ form.clubdescription(id="inputthedescription") }}
            </div>
        </div>
        <div class="button">
            {{ form.submit(class="submitnewclubbutton", onclick="loading();") }}
        </div>
    </form>
</div>

{% endblock %}

website/templates/searchresults.html
{% include "clubcard.html" %}